### PR TITLE
Add Romm to Games

### LINKED ISSUE #3720: Add romm to Games
Been using this one for the past few weeks

https://github.com/zurdi15/romm

Its a game rom management library.

### PR DESCRIPTION
**Pull request by kokomo123**
This should close #3720, if this doesn't fit in Games, or if there's any corrections, concerns, let me know! 

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding has working installation instructions.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by Rabenherz112** [comment]
Should this count under Games? From my understanding, it is only a ROM Manager, but it can't be used to play something.

**Comment by Rabenherz112** [comment]
Also, duplicate to https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3879.
However feel free to review the PR

**Review by nodiscc — APPROVED** [review]

**Comment by kokomo123** [comment]
> Also, duplicate to #3879. However feel free to review the PR

I didn't see this, oops! Sorry about that.

**Comment by Rabenherz112** [comment]
> I didn't see this, oops! Sorry about that. I mean i could move it all the way to misc if needed, otherwise I guess it's safe to add it to games for now?

I mean nodiscc approved it, so it will be probably fine as it is.

**Comment by nodiscc** [comment]
PR https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3879 closed in favor of this one (which is correctly formatted and has a better description).

**Pull request merged**
