### PR TITLE
Update language tags - Part 2

### PR DESCRIPTION
**Pull request by Rabenherz112**
ref: #3945 

Edit: Next up: Feed Readers

### CODE REVIEW

**Comment by Rabenherz112** [comment]
Could someone kindly review "Tokumei"?  I'm a bit puzzled because the language mentioned is 'rc', which I don't know what this is. Upon examining the installer, it appears to be more like Go? Currently, I'm a bit confused their..

**Comment by nodiscc** [comment]
> Could someone kindly review "Tokumei"? I'm a bit puzzled because the language mentioned is 'rc', which I don't know what this is. Upon examining the installer, it appears to be more like Go? Currently, I'm a bit confused their..

The project README reads:

> Tokumei is written in rc, the Plan 9 shell, using the werc minimal web framework

**https://en.wikipedia.org/wiki/Rc**

The main installation script can be found at https://tokumei.co/hosting/private-clearnet -> https://tokumei.co/privclear.sh. It looks designed for Debian-based systems and uses `apt` to install the [9base](https://packages.debian.org/bookworm/9base) packkages which contains the `rc` interpreter. It clones Tokumei sources (definitely written in `rc` shell https://gitlab.com/tokumei/tokumei/-/tree/master/bin), installs https://github.com/uriel/cgd which is a FastCGI server that serves exposes the `rc` shell application as a HTTP service on local port 3333, installs an nginx configuration that redirects HTTP requests to cgd. `cgd`  is written in go but is only used as a middleware, not the main application. So `rc` is correct.

But anyway this project has been unmaintained since 2017 (https://gitlab.com/tokumei/tokumei/-/commits/master?ref_type=heads), and cgd is unmaintained since 2012. I think it's safe to remove it.

**Comment by Rabenherz112** [comment]
I found "VanDAM" in the "Document Management - E-books" section.
As it describes itself, it seems an asset/file manager with nothing related to E-Books:
> VanDAM is a Digital Asset Manager (DAM), specifically designed for 3D print files

Should we move it from there to Miscellaneous?

**Comment by nodiscc** [comment]
> VanDAM is a Digital Asset Manager (DAM), specifically designed for 3D print files
>Should we move it from there to Miscellaneous?

I think this was overlooked when it was submitted (https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3652). It should definitely be moved, thank you.

**Comment by nodiscc** [comment]
Great work, thank you. Can you please resolve merge conflicts?

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
