### PR TITLE
Add Homarr under Personal Dashboards

### PR DESCRIPTION
**Pull request by Lissy93**
This PR adds Homarr (not to be confused with Homer!), which is a self-hosted personal dashboard built by @ajnart

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by ajnart** [comment]
Thank you so much for this @Lissy93 ! How is the demo broken for you ? it's a very basic demo where the config is read only, hence why it resets on page load , also you can't display integrations unless having them publicly available (via an https page, cloudflare or self hosted CA) because the server won't have access to your localhost

**Comment by ajnart** [comment]
> No worries @ajnart, nice work you've done :)
> 
> ---
> 
> I've not looked into it too far, but on load I see `n.services.filter(...).at is not a function` (on Chromium incognito and Brave)
> 
> image
> 
> 

To be honest I don't know why this would happen in incognito mode. Maybe it disallows cookies by default ? I'm not really sure how to fix the code so it would work in Incog mode

**Comment by Lissy93** [comment]
It happens in normal mode too, I just used Incognito mode to double check it wasn't a local storage, cookie or extension issue.

But can confirm it works okay in Firefox, and on non-Linux systems, so maybe it's just me.

**Review by KieranRobson — CHANGES_REQUESTED** [review]
Congratulations on adding your contribution!

The description is a little vague and could be used for each of the dashboards, in line with the repo could you change the description to:
`A simple and lightweight homepage for your server, that helps you easily access all of your services in one place.`

**Comment by ajnart** [comment]
I would personally refer to Homarr as : `a small modular homepage for your server that offers direct communication with other self hosted services and has the fly configuration`

**Comment by ajnart** [comment]
> It happens in normal mode too, I just used Incognito mode to double check it wasn't a local storage, cookie or extension issue.
> 
> But can confirm it works okay in Firefox, and on non-Linux systems, so maybe it's just me.

I'll do more testing on Linux. It works fine on my end with Arch / Ungoogled chromium and Firefox.

**Review by KieranRobson — APPROVED** [review]

**Comment by Lissy93** [comment]
But I do semi-agree that it's probably no practical to add all the newly emerging apps, and that quality control is important.

**Comment by manuel-rw** [comment]
Hello. We just released Homarr ``0.11.2``. In the last few months, we've worked hard on major improvements and added a drag and drop system. I think this is quite a unique feature of Homarr, since not many other dashboards have this. For this reason, I would like to ask if we can re-open this?

**Pull request closed without merging**
