### PR TITLE
Add Loggit to Miscellaneous

### PR DESCRIPTION
**Pull request by BrunoBernardino**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Miscellaneous`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another project, please provide/link to a clear list of differences between both.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by nodiscc** [comment]
> Any software project you are adding was first released more than 4 months ago.

There are no tagged releases. Given this, I don't think it should be added, because it implies users are running a development/unstable version at all times (`make run` from main).

**Comment by BrunoBernardino** [comment]
@nodiscc thanks! Indeed the version available in the hosted web app will be the latest, as that's common for web apps. Would it help if I added a tag/release for the "3.0" release? The commit would be https://github.com/BrunoBernardino/loggit-web/commit/56a9f191d2b2eda1d920f109adc30484df022932 , for example.

**Comment by nodiscc** [comment]
> Would it help if I added a tag/release for the "3.0" release?

Yes.

**Comment by BrunoBernardino** [comment]
There you go: https://github.com/BrunoBernardino/loggit-web/releases https://github.com/BrunoBernardino/loggit-web/releases/tag/v3.0.0 for the first self-hostable one, released on February 19th, and https://github.com/BrunoBernardino/loggit-web/releases/tag/v3.1.0 released 5 days ago.

**Comment by nodiscc** [comment]
- https://github.com/BrunoBernardino/loggit-web#self-host-it only has setup instructions for proprietary PaaS. Where can I find actual self-hosted installation documentation?
- From the description this seems to be a frontend for the Loggit service, correct? Where is the source code for the backend/where does it store user data?

**Comment by BrunoBernardino** [comment]
> Where can I find actual self-hosted installation documentation?

The [development section linked in there has the commands to start the app, wherever they want](https://github.com/BrunoBernardino/loggit-web#development).

> From the description this seems to be a frontend for the Loggit service, correct?

No. Where do you see that? It's a regular app, so https://github.com/BrunoBernardino/loggit-web/blob/main/pages/index.ts is the "index" page, where you can see most HTML, which includes a `<script>` tag to https://github.com/BrunoBernardino/loggit-web/blob/main/public/ts/index.ts as the "frontend JS" code.

> Where does it store user data?

In the indicated postgres database, that's booted with `docker-compose up`. [It's explained in the requirements section](https://github.com/BrunoBernardino/loggit-web#requirements).

**Comment by KieranRobson** [comment]
> The [development section linked in there has the commands to start the app, wherever anyone want](https://github.com/BrunoBernardino/loggit-web#development).

For people to install and run, there should be actual installation documentation that an average person who isn't looking to develop may miss.

**Comment by BrunoBernardino** [comment]
> For people to install and run, there should be actual installation documentation that an average person who isn't looking to develop may miss.

I don't understand what's missing from the [requirements section](https://github.com/BrunoBernardino/loggit-web#requirements), could you please elaborate? Is it about installing Docker or docker compose, or Caddy, or Deno? I link to most of those tools in there.

**Comment by nodiscc** [comment]
> The development section linked in there has the commands to start the app, wherever anyone want

Ok. I find it confusing that this information is under a `Development` section, and not under `Deployment`. It make it look like the self-hosted setup is not ready for production/should only be used for development purposes. 

> From the description this seems to be a frontend for the Loggit service, correct?
>> No. Where do you see that? It's a regular app

The description says "This is the web app for the [Loggit app](https://loggit.net/),", which lead me to believe 1. it somehow depended on loggit.net 2. it's "only" the web app component/implying there are other components. I understand from your reply that it's actually the only component (except the database), so fine.

Approving anyway, but you may want to clarify these points in the documentation.

Thanks!

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
