### PR TITLE
Add theme.park

### PR DESCRIPTION
**Pull request by hasecilu**
An awesome collection of themes for self-hosted apps. [The main website](https://theme-park.dev/) have a button that says CLICK ME! and kind of function as a demo.
Is active, has excellent instructions.
Added to misc category.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding has working installation instructions.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by Rabenherz112** [comment]
This is a very fantastic resource for changing the design of other applications. However, I don't know how to integrate this into this list, as it is not an application or software which can be hosted but rather a resource that provides CSS templates.

Maybe nodiscc could say more to this.

**Comment by nodiscc** [comment]
Thanks @Rabenherz112 for the review.

Correct, it doesn't seem fitting to list this alongside other applications. Even the `Miscellaneous` category doesn't seem appropriate. Maybe it should be moved to https://github.com/awesome-selfhosted/awesome-selfhosted#external-links?

**Comment by Rabenherz112** [comment]
That would probably be the best possibility. A separate point in the external links would solve the problem.

**Comment by hasecilu** [comment]
Thanks for the review, would it need any additional formatting or just moving it is enough?

**Review by nodiscc — APPROVED** [review]

**Review by Kaktrollet — COMMENTED** [review]
Jj

**Pull request merged**
