### PR TITLE
Remove peppermint (unmaintained since 2022) from Ticketing

### PR DESCRIPTION
**Pull request by Rabenherz112**
Peppermint appears to have been unmaintained since 2022, as evidenced by multiple open security vulnerability issues that have been unresolved since July 2022 (https://github.com/Peppermint-Lab/peppermint/issues/105, https://github.com/Peppermint-Lab/peppermint/issues/106). Additionally, the project suffers from outdated dependencies in the package.json file. The last release of Peppermint was in February 2022, indicating a lack of recent updates and improvements.

An Issue has been created in the repository:
https://github.com/Peppermint-Lab/peppermint/issues/143

ref: #3558

### CODE REVIEW

**Review by nodiscc — APPROVED** [review]
Thanks

**Comment by Rabenherz112** [comment]
Reply by @potts99
> Hey mate, no not dead, new beta for next major udpate coming sunday

**Comment by nodiscc** [comment]
> new beta for next major udpate coming sunday

Putting this on hold

**Comment by potts99** [comment]
This isnt unmaintaned :) theres actually a release coming tonight/tomorrow

**Comment by nodiscc** [comment]
> This isnt unmaintaned

How do you explain the absence of reply on these security issues then? (`Path Traversal - Arbitrary File Deletion (unauthenticated)` and `Account Takeover - Arbitrary Password Change (unauthenticated)`)

**Comment by potts99** [comment]
Lack of time, manpower, motivation and help :) which have all been corrected

**Comment by potts99** [comment]
These have been rectified to my knowledge in a latest version, at least the account one is, I'll sort the prs out and get them closed

**Comment by The-Tru-th** [comment]
Could someone explain to me what's going on? Which application has the
phone number application? What has the vulnerabilities to git hub app? Dm
me if possible Because I've been using this app for a little while. And
almost every phone, I've downloaded it on somehow They always end up hacked
the very first. They embedded the software on my device. It didn't have
anything to do with this app. It actually showed me who the people were,
but but now that all of that has passed, something happens to my phones
every time.  I give this app permission basically handling my data and
things of that nature.
Other than getting off of the website. Is there a way to protect from these
vulnerabilities? To keep them from getting into my device.  I'm trying to
see what's going on Because phones are not cheap. I literally had 1 person
make my phone where it stopped charging.
Amongst many other things, it's been going on for about a year now and I'm
tired of my privacy. Be invaliated experience has unfound every bit of my
information on the dark web.

**Pull request closed without merging**
