### PR TITLE
Update Standard Notes domain

### PR DESCRIPTION
**Pull request by mobitar**
We've moved to .com :)

### CODE REVIEW

**Comment by slel** [comment]
But the demo link stays at .org?

**Comment by mobitar** [comment]
Yup for now. We're doing the migration in parts :)

**Comment by slel** [comment]
The page https://github.com/standardnotes
has a header with the new .com home url.
The docs url there could be updated too
since it already redirects from .org to .com.
And the help email if/when it has migrated.

**Comment by mobitar** [comment]
Docs domain updated 👍

Help email currently can receive at help@standardnotes.com. We're currently in the process of making that the primary email domain as well.

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
