### PR TITLE
Add qwantify to 'Games - Administrative Utilities & Control Panels'

### PR DESCRIPTION
**Pull request by WebSnke**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Review by kokomo123 — CHANGES_REQUESTED** [review]
Please do Docker/Go as it's using docker containers. Thank you! 👍🏻

**Comment by WebSnke** [comment]
> Please change the language to Docker/Go as it's using docker containers. Thank you! :)

Done. Thanks for the suggestion.

**Comment by kokomo123** [comment]
you can keep the go, just you can do Docker/Go as the language instead of just Docker or Go

**Comment by kokomo123** [comment]
Almost there, it's Docker slash Go haha.

**Review by kokomo123 — APPROVED** [review]
Excellent! Thanks so much 💯

**Comment by WebSnke** [comment]
> Excellent! Thanks so much 💯

You're welcome. 💯

**Comment by fbartels** [comment]
I saw this posted on Reddit today as well. What is the exact benefit compared to [neko](https://github.com/m1k1o/neko)? Looking at the diff changes seem mostly to be in the docker area, but not so much in the actual code. The repo linked here is a GitHub for of https://github.com/wanjohiryan/qwantify, which is a fork of neko. Why the fork of a fork?

**Comment by WebSnke** [comment]
> Why the fork of a fork?

Yeah, that was a mistake. I fixed it in a new commit.

**Comment by nodiscc** [comment]
Why fork Neko in the first place? Have you tried upstreaming your changes?

> Rent out your GPU

Does this work without renting a GPU from you?

**Comment by WebSnke** [comment]
> What is the exact benefit compared to [neko](https://github.com/m1k1o/neko)?

Yeah, I don't think that we should add it. It doesn't seem to be free as in freedom and it is also still in public alpha.

**Pull request closed without merging**
