### PR TITLE
Add Earthwalker to Games

### PR DESCRIPTION
**Pull request by claabs**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Review by nodiscc — COMMENTED** [review]
It 100% depends on Google Maps and Street View (and might be in violation of their ToS?), so I don't think it is a good candidate for the list - though a geoguessr alternative is a nice project

**Comment by claabs** [comment]
There are other projects on the list that depend on a proprietary service, and it's indicated by the `⚠`.

The TOS violation is a valid concern. It's addressed in the [project's readme](https://gitlab.com/glatteis/earthwalker#disclaimer). It effectively just proxies Google Maps web requests. I understand if that's enough to close PR.

**Comment by nodiscc** [comment]
ToS compliance is not the main problem (props for adding a warning to the README), but the fact that the software is 100% unusable without Google Street View data and that most of the traffic from users goes to a non-free, non self-hostable service using non-free data. We do list other projects that depend on a proprietary service, but not (I think?) at this level of dependency.

The "easy" way out of this would be making it compatible with equivalent Free/Libre services, but I think no such thing exists (https://wiki.openstreetmap.org/wiki/OpenStreetView_(2009) ? ), and given the effort it would take I totally understand if you don't do that.

Or maybe I'm wrong and we should add it. But it sets a dangerous precedent ("hey please add my self-hosted app: `<iframe src="https://www.google.com"></iframe>`" if we take it to the extreme). More input welcome

**Comment by claabs** [comment]
> the fact that the software is 100% unusable without Google Street View data

I'd say it's more like 80% unusable without Street View. You can still view the results of past challenges, and create/browse maps without it. The 2D map viewer's tileserver is configurable, so it can be anything from OpenStreetMaps to Google Maps. 

> We do list other projects that depend on a proprietary service, but not (I think?) at this level of dependency.

I'd argue that the various "front-end rewrite" or SaaS-enhancement projects on the list are good examples of software that 100% depend on proprietary services. Earthwalker may be more akin to the projects that depend on proprietary data sources, like TheTVDB.

**Comment by nodiscc** [comment]
> You can still view the results of past challenges, and create/browse maps without it. The 2D map viewer's tileserver is configurable, so it can be anything from OpenStreetMaps to Google Maps.

:+1: 

> I'd argue that the various "front-end rewrite" or SaaS-enhancement projects on the list are good examples of software that 100% depend on proprietary services.

Which ones?

> more akin to the projects that depend on proprietary data sources

But in this case it's not only data, right? The JS responsible for displaying/controlling the "Street View" functionality is entirely hosted on Google's servers, correct? Or did you re-implement that, and only pull street view photographic data from G?

Again I'm not entirely against adding it to the list, but it opens the gates to projects that do most of the compute/host JS on non self-hosted, non-Free services, and someone will inevitably submit something like the shady iframe example I posted earlier. The line has to be drawn somewhere.

Related to https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2705

**Comment by nodiscc** [comment]
After thinking about it for a while, I don't think we should add it.

But I opened an issue at https://github.com/osmlab/awesome-openstreetmap/issues/112 to get it added there instead, and awesome-openstreetmap is linked from https://github.com/awesome-selfhosted/awesome-selfhosted#maps-and-global-positioning-system-gps.

**Pull request closed without merging**
