### PR TITLE
Add YoutubeDLServer to Automation

### LINKED ISSUE #2380: Add youtube-dl-server
https://github.com/manbearwiz/youtube-dl-server
Python/Docker
MIT
Web and REST interface for downloading videos onto a server.
Automation

### PR DESCRIPTION
**Pull request by kokomo123**
As requested, this should be able to fulfill and close #2380. After one year I'm glad to satisfy and close this issue. 

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by nodiscc** [comment]
Aside from automated dependency updates, this project has not seen any kind of maintenance for a few months (https://github.com/manbearwiz/youtube-dl-server/commits/master), issues are left untriaged/unanswered, and more importantly security-related issues are left unanswered: https://github.com/manbearwiz/youtube-dl-server/issues/100

I think this used to be mentioned in [contributing](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md) guidelines, but cannot find any mention of it anywhere: projects with persistent, unaddressed security issues should not be added to the list. The issue might not be serious at all (or even real) but it's still concerning that there was no feedback over this since July.

Let's wait for an update from @manbearwiz.

**Comment by kokomo123** [comment]
Well in all honesty, I probably should inspect the repository now more before making a PR despite the issue being open and no one ever made a PR to complete these.

**Comment by nodiscc** [comment]
>  Any software project you are adding to the list is actively maintained.

"actively maintained" includes addressing security issues, or at least acknowledging/triaging them, yes.

> should inspect the repository now more before making a PR

That's why reviews are time consuming, but don't worry, your help is greatly appreciated. It would be _very_ hard to automate this. Thanks again.

**Comment by nodiscc** [comment]
Same situation as before, no active maintenance, closing.

**Pull request closed without merging**
