### PR TITLE
Remove Dovel (source code unreachable)

### PR DESCRIPTION
**Pull request by nodiscc**
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3558
- `https://blmayer.dev/x/dovel : HTTP 500` or `(52) Empty reply from server`

### CODE REVIEW

**Comment by blmayer** [comment]
Hey, I changed the development platform, now the git is in https://git.derelict.garden/dovel/email. Sorry I forgot to update it here. I can create a PR to update this if you wish.

**Comment by nodiscc** [comment]
>  I can create a PR to update this if you wish.

That would be nice, thanks. You can point the source code link at https://git.derelict.garden/dovel/email/tree directly.

**Comment by blmayer** [comment]
Thanks, this is the PR: #4029.

**Pull request closed without merging**
