### PR TITLE
Add BlueCap, BluetoothCommunicator and SmartGattLib to CommunicationSystems/Bluetooth

### PR DESCRIPTION
**Pull request by niedev**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements (`Demo` and `Clients` are optional, don't add a duplicate `Source code` link if it is the same as the main link):

``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [ ] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and marked `⊘ Proprietary`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] The `Language` tag is the main server-side requirement for the software - don't include frameworks/specifc dialects.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is "Add aaa to bbb" for adding software aaa to section bbb. Do not call it "Update README.md".

### CODE REVIEW

**Comment by nodiscc** [comment]
These are low-level libraries for bluetooth, unrelated to self-hosting.

**Comment by niedev** [comment]
@nodiscc Ok, actually SmartGattLib and BlueCap are a bit off-topic, but my library (BluetoothCommunicator) is not low-level and its only purpose is to allow communication between Android devices so it can be a valid alternative to a communication via server.

I created it just to avoid having to use a server for communication between devices in my app (RTranslator).

If, in addition to BluetoothCommunicator, I add 2 other libraries that allow P2P communication via Bluetooth, would you accept my request?

**Comment by nodiscc** [comment]
@niedev well I am open to all options, but keep in mind that the software must be directly installable/distrbuted in a ready-to-use (or build) form. If the platform is android this probably means distributing a .apk package (or a way to build it) on your releases pages or on [f-droid](https://f-droid.org/), etc. i.e no "You have to write your own android app and integrate my library". if you can release a simple app demonstrating basic P2P-over-bluetooth functionality that would qualify.

In doubt, I suggest sending Pull Requests with a single item, so that a question about a project does not block adding others.

**Comment by niedev** [comment]
@nodiscc I already did it, in the description I had included a demo for BluetoothCommunicator ([BluetoothCommunicatorExample](https://github.com/niedev/BluetoothCommunicatorExample)), it is a Bluetooth chat app. Did I have to enter the apk directly into the BluetoothCommunicator GitHub page? Or should I directly propose the demo app instead of the library? (the app is only a demo, it doesn't have many features).

Ok, next time I will send 3 separate pull requests or a single one in an existing category.

**Comment by nodiscc** [comment]
> should I directly propose the demo app instead of the library? (the app is only a demo, it doesn't have many features).

Yes you should do this (but either add a link to the apk on the BluetoothCommunicatorExample page, or provide build instructions)

**Comment by niedev** [comment]
Ok, thank you! In the next days/weeks I will update the readme with the link to the apk and I will do the pull request.

**Pull request closed without merging**
