### PR TITLE
Added EmbassyOS to Self-hosting Solutions

### PR DESCRIPTION
**Pull request by kn0wmad**
To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where Demo and Clients are optional.
Do not add a duplicate Source code link if it is the same as the main link.
Keep the short description under 250 characters and use sentence case
for it, even if the project's webpage or readme uses another capitalisation
such as title case, all caps, small caps or all lowercase.
- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language`
- [x] Additions that depend on proprietary services outside the user's control must be marked ⚠.
- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language`
- [x] Additions that are not Free software
must be added to non-free.md and marked ⊘ Proprietary:
- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of

    awesome-sysadmin (IT infrastructure management),
    awesome-analytics (analytics),
    staticgen.com
    staticsitegenerators.net (static site generators).

- [x] The Language tag is the main server-side requirement for the software - don't include frameworks or specific dialects.
- [ ] Any license you add is in our list of licenses.
- [x] You have searched the repository for any relevant issues or PRs, including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
If not, your addition may be inserted into Misc/Other.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
"Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by jherazob** [comment]
The license is "START9 PERSONAL USE LICENSE v1.0", can't check now but is this actually Free Software? or just "free" in quotes? If so it should go to non-free

**Comment by kn0wmad** [comment]
> The license is "START9 PERSONAL USE LICENSE v1.0", can't check now but is this actually Free Software? or just "free" in quotes? If so it should go to non-free

Anyone can download and build the device for personal use for free as in beer and freedom.  Does this answer the question?  Thank you for your time :)

**Comment by jherazob** [comment]
So, it should go to non-free then

**Comment by kn0wmad** [comment]
> So, it should go to non-free then

I'm sorry, but I don't understand why this is non-free?  According to the wikipedia presented as a definition for 'free software,' it would seem that our software is free.

**Comment by jherazob** [comment]
Sorry, i'm not a maintainer so i have no say on this, just commenting. From what i read then yes, you have the code, but the restriction for commercial works would not let it pass the Debian Free Software Guidelines for example (it would go unquestionably to "non-free" there like many other programs with code but with restrictions before), and i'm not sure about the FSF. And the restriction against distributing "object code" (compiled binaries, right?) would restrict it even further, to the point that it would never hit distro repos (except maybe Arch i guess). Yes, you can install it on your machine, but always compiled from code. This is an unusual case so i guess it's worth a discussion.

**Comment by kn0wmad** [comment]
> Sorry, i'm not a maintainer so i have no say on this, just commenting. From what i read then yes, you have the code, but the restriction for commercial works would not let it pass the Debian Free Software Guidelines for example (it would go unquestionably to "non-free" there like many other programs with code but with restrictions before), and i'm not sure about the FSF. And the restriction against distributing "object code" (compiled binaries, right?) would restrict it even further, to the point that it would never hit distro repos (except maybe Arch i guess). Yes, you can install it on your machine, but always compiled from code. This is an unusual case so i guess it's worth a discussion.

There is no mention of Debian or FSF guidelines in the contribution requirements.  I'll wait for a maintainer.  Thank you for the comments

**Comment by nodiscc** [comment]
Hi all

> https://www.gnu.org/philosophy/free-sw.html
> The freedom to run the program as you wish, for any purpose

> https://opensource.org/osd-annotated
> https://www.debian.org/social_contract#guidelines
> 6. No Discrimination Against Fields of Endeavor
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

Going by these 3 widely accepted sources, restricting commercial use of software makes it non-Free ( _for any purpose_). Thats why we have `CC-NC-BY-SA` licensed software in non-free.md.

> the License does NOT grant you the right to:
>Distribute the Object Code.

So I can't redistribute the binaries I built?

>    Sell the Software or any derivative works based thereon.

In opposition to freedom 0.

Have you considered AGPL or other strong copyleft licenses? It depends what you want to achieve. But restricting allowed uses of software or its distribution would make it go to non-free. Looks like a nice project by the way.

**Comment by kn0wmad** [comment]
> Hi all
> 
> > https://www.gnu.org/philosophy/free-sw.html
> > The freedom to run the program as you wish, for any purpose
> 
> > https://opensource.org/osd-annotated
> > https://www.debian.org/social_contract#guidelines
> > 6. No Discrimination Against Fields of Endeavor
> > The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.
> 
> Going by these 3 widely accepted sources, restricting commercial use of software makes it non-Free ( _for any purpose_). Thats why we have `CC-NC-BY-SA` licensed software in non-free.md.
> 
> > the License does NOT grant you the right to:
> > Distribute the Object Code.
> 
> So I can't redistribute the binaries I built?
> 
> > Sell the Software or any derivative works based thereon.
> 
> In opposition to freedom 0.
> 
> Have you considered AGPL or other strong copyleft licenses? It depends what you want to achieve. But restricting allowed uses of software or its distribution would make it go to non-free. Looks like a nice project by the way.

Changes have been made to reflect "non-free"

**Review by nodiscc — APPROVED** [review]

**Comment by nodiscc** [comment]
> The description for the non-free section of this website makes it sound like EmbassyOS is closed source, can't be run for free, can't be audited, and is likely dangerous - none of which is true - and all of which can be independently verified by anyone.

> There are massive benefits to OSS over closed source.

This is true, the non-free.md description paragraph should be updated to mention source-available software.

**Comment by nodiscc** [comment]
Related: https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2689

**Pull request merged**
