### PR TITLE
Updated to new link for Awesome Sysadmin

### PR DESCRIPTION
**Pull request by UnixNight**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of
  - [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management),
  - [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics),
  - [staticgen.com](https://www.staticgen.com/)
  - [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [ ] The `Language` tag is the main server-side requirement for the software - don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by Codel1417** [comment]
I would prefer to not support their decision to overcomplicate a simple list

**Comment by Codel1417** [comment]
maybe @awesome-selhosted can fork and maintain the sysadmin liat

**Comment by nodiscc** [comment]
on hold, see https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2482 for discussion on what to do about awesome-sysadmin

**Comment by n1trux** [comment]
I vote against merging this PR and **for** finding a proper solution for #2482 instead. These lists are just "star farming" on Github, which is totally useless for sharing information.

> I would prefer to not support their decision to overcomplicate a simple list

That you think a forum is more complicated than fucking Github insults my intelligence. I, too, think that the (current) forum is not the proper way to do things. I also think Github is way too overblown. You're comparing a a Git interface with a markdown renderer with thousands of useless features with a simple forum. At this point, even a mailing list with discussions and a git repo would be better. If you like the format of a link list with descriptions better, I'll be happy to replace the forum with a MD renderer of your choice.

**Comment by reddec** [comment]
Why we can not be based Github Pages in this repo based on content? Single .md file for each section with full-text search and proper navigation I guess will help everyone. In that case, it looks like a good idea to even merge the old awesome-sysadmin repo under another section just here.

**Comment by Codel1417** [comment]
@n1trux you can do alot on github without ever touching a command line.

**Comment by nodiscc** [comment]
Blocked by https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038

**Comment by arfahmd** [comment]
thanks

**Comment by nodiscc** [comment]
The link has been updated to https://github.com/awesome-foss/awesome-sysadmin, see https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2482 for remaining issues about awesome-sysadmin.

**Pull request closed without merging**
