### PR TITLE
Adjust Tiny Tiny RSS Programming Language

### LINKED ISSUE #3372: Tiny Tiny RSS now supports only `Docker`
Tiny Tiny BBS now supports only `Docker`. Could anyone create PR?

### PR DESCRIPTION
**Pull request by kokomo123**
This should close #3372 as requested. :)

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by mzch** [comment]
TTS doesn't support using PHP but only `Docker`. I think `PHP` should be removed.

**Comment by kokomo123** [comment]
Nodiscc said it could be used as PHP/Docker but if docker is only needed ill add that. Not sure but i figured i would do that.

**Comment by mzch** [comment]
@KieranRobson says, 'As docker is the only documented install method, please change the langauge tag to docker' in my Short{Page} PR. See #3220 .

**Comment by kokomo123** [comment]
You mean Tiny Tiny RSS? I run it with a simple php-fpm/postgres/apache setup [[1]](https://github.com/nodiscc/xsrv/tree/master/roles/tt_rss), but yes, Docker is now the recommended method, we could change it to Docker/PHP per nodiscc. so hm. I suppose we could just do docker then, fair point.

**Comment by mzch** [comment]
Wel, it seems that each moderator instructs differently. What do @KieranRobson  and @nodiscc thnk it?

**Comment by kokomo123** [comment]
We can wait for their opinion but I dunno, either or is fair to me.

**Comment by nodiscc** [comment]
https://tt-rss.org/wiki/InstallationNotesHost

**Comment by kokomo123** [comment]
Fixed, all sorted. Thanks for clarifying nodiscc.

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
