### PR TITLE
Add Komga

### PR DESCRIPTION
**Pull request by gotson**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> Language/platform should be `Java/Docker`

But Kotlin is its own language which is similar to java.

**Comment by nodiscc** [comment]
> But Kotlin is its own language which is similar to java.

Running the program requires a JVM, hence `Java`

**Comment by SuperSandro2000** [comment]
The pull request template states `Language` and the project ist written in Kotlin not Java. This is confusing and not quite right. Right now it is a mixture between maybe the language the program is written in or maybe something it requires to run which makes no real sense and is confusing. If I write something for JRuby it is still ruby and not java code. Also if we would list all requirements we would need to add C to basically anything cause almost all the things require something written in C.

Also then this would need a change to JS.
````
EteSync Web - EteSync's official Web-based client (i.e., their Web app). (Demo, Source Code) AGPL-3.0 TypeScript
````

**Comment by gotson** [comment]
I feel like my PR raised some internal questions :)

Let me know what you decide and i'll update accordingly.

**Pull request merged**
