### PR TITLE
Add Pad

### PR DESCRIPTION
**Pull request by darkdragon-001**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [ ] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [ ] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Pad is a terrible name for a pad software.

**Comment by darkdragon-001** [comment]
> Pad is a terrible name for a pad software.

Agree. I am not the creator of the app though. I asked for a better name in petercunha/Pad#13.

**Comment by miloskroulik** [comment]
Also, it looks like it's not developed anymore.

**Comment by darkdragon-001** [comment]
@miloskroulik There is not too much to develop on such a simple system any more. It is working fine for me so far and the best alternative I could find.

**Comment by SuperSandro2000** [comment]
js dependencies are getting outdated over time which is something you not really want to face to the internet.

**Comment by darkdragon-001** [comment]
Just running `npm update` should fix this. And this is still a lot less work than writing such an application from scratch...

**Comment by darkdragon-001** [comment]
@SuperSandro2000 Dependencies are checked automatically with [dependabot](https://help.github.com/en/github/administering-a-repository/about-github-dependabot).

**Comment by SuperSandro2000** [comment]
> Just running npm update should fix this.

Which could break stuff and then you would need to hunt down bugs.

>  If there were 10 alternatives, the situation would be different.

Its not about alternatives, it is about awesomeness and the next guy that checks this project submits a PR that it is dead.

**Comment by nodiscc** [comment]
It would be better to ask the author if they intend to maintain the software (eg. update dependencies once in a while), or if it can be considered abandoned. Last commit is more than one year ago.

**Comment by darkdragon-001** [comment]
> It would be better to ask the author if they intend to maintain the software (eg. update dependencies once in a while), or if it can be considered abandoned. Last commit is more than one year ago.

I [asked](https://github.com/petercunha/Pad/issues/18) about it.

**Comment by nodiscc** [comment]
No reply to issue https://github.com/petercunha/Pad/issues/18 opened +1 month ago. Feel free to reopen this pull request if you can confirm the software is actively maintained.

**Pull request closed without merging**
