### PR TITLE
added temporary.chat

### PR DESCRIPTION
**Pull request by ba9f11ecc3497d9993b933fdc2bd61e5**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> Since the initial submission of the proposal, there have been no subsequent updates or improvements made to the project. Additionally, I find the installation and deployment instructions provided not really sufficient, at least from my perspective. Following the instructions in the readme and without Google, I couldn't set up the chat system (However this might just be for me an Issue since I have no familiarity with Jinja).

It is correct I did not update the project for a long time.

Can I know where you encounter an issue deploying? (jinja knowledge is not required) It could help me improve the README

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
ah, what is perhaps not clear is that you deploy to your remote empty server

deployment machine (your regular box)     ---------------------------> empty ubuntu server with the requirements
[ansible-playbook]                                                                                [ssh public key installed for user ubuntu]
[inventory]                                                                                              [/etc/sudoers file allowing ubuntu to sudo without pass]
[ssh private key]

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
running the config helper https://github.com/ba9f11ecc3497d9993b933fdc2bd61e5/temporary.chat-playbook/blob/master/config_helper.sh should generate both your ssh config (on the deployment machine) and the inventory file (also on your deployment machine)

the deployment machine only needs to be able to ssh to the empty ubuntu server to configure it

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
and to get the ansible-playbook command on your deployment machine : https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html

**Comment by Rabenherz112** [comment]
> ah, what is perhaps not clear is that you deploy to your remote empty server from another machine (push model)
> 
> on your deployment machine (your regular box) :
> [ansible-playbook]
> [inventory]
> [ssh private key]
> 
> on the empty ubuntu server :
> [ssh public key installed for user ubuntu]
> [/etc/sudoers file allowing ubuntu to sudo without pass]

Oh, now I get it.. Didn't read that out from the instructions which were provided. This makes now a lot more sense.

**Comment by Rabenherz112** [comment]
The only big issue I still have with this project, apart from the instructions being a little too short, is the following sentence in your setup instructions.
> having a user named ubuntu on the server that is allow to sudo without a password (will change this to a variable)

From a security perspective, this choice appears highly problematic. Since the server needs to be accessible from the Internet to serve the Chat App online, it is unlikely that most users would take measures to block logins from the Internet. Combining this with the requirement of using the easily guessable "ubuntu" username, creates a significant security vulnerability during the installation process, at least in my opinion.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> The only big issue I still have with this project, apart from the instructions being a little too short, is the following sentence in your setup instructions.
> 
> > having a user named ubuntu on the server that is allow to sudo without a password (will change this to a variable)
> 
> From a security perspective, this choice appears highly problematic. Since the server needs to be accessible from the Internet to serve the Chat App online, it is unlikely that most users would take measures to block logins from the Internet. Combining this with the requirement of using the easily guessable "ubuntu" username, creates a significant security vulnerability during the installation process, at least in my opinion.

If the ssh server only allows asymetric key pairs as a way of login, it is safe. If you want to restrict this further down, you can limit ssh to the specific ip of the deployment machine. I have this other ansible recipe to "prep" your server

https://github.com/ba9f11ecc3497d9993b933fdc2bd61e5/vultr_prep

it was made for a vultr vps, but it will work with any machine

I made some assumptions on the level of technical knowlege of the target audience (sudo, ssh, firewall) but you are right, I could add to the readme : "allowing the ssh port from the deployment machine only"

**Comment by Rabenherz112** [comment]
> I made some assumptions on the level of technical knowlege of the target audience (sudo, ssh, firewall) but you are right, I could add to the readme : "allowing the ssh port from the deployment machine only"

Personally, I know individuals who browse this list with the aim of hosting intriguing projects, yet they may not possess an advanced level of technical knowledge or a deep understanding of security practices (which is a good thing). Consequently, when you add this project to the list, I think it is crucial to anticipate that less knowledgeable individuals may come across it. Therefore, the instructions, when followed as provided, should not create a security vulnerability by default. I guess you could also instead of changing the code, just add another part to explain the best-practice (only allow specific ssh keys or ips), but even that would need to be linked at least to some tutorial.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> > I made some assumptions on the level of technical knowlege of the target audience (sudo, ssh, firewall) but you are right, I could add to the readme : "allowing the ssh port from the deployment machine only"
> 
> Personally, I know individuals who browse this list with the aim of hosting intriguing projects, yet they may not possess an advanced level of technical knowledge or a deep understanding of security practices (which is a good thing). Consequently, when you add this project to the list, I think it is crucial to anticipate that less knowledgeable individuals may come across it. Therefore, **the instructions, when followed as provided, should not create a security vulnerability by default**. I guess you could also instead of changing the code, just add another part to explain the best-practice (only allow specific ssh keys or ips), but even that would need to be linked at least to some tutorial.

Although you are right, I think explaining how to configure/secure ssh and  configure/secure a firewall might be a bit too much for the users with less technical knowledge. What I could do instead is deploying directly from the target machine (ansible using localhost as a target) that would remove the need for ssh altogether (but I am unsure how the user will manage the server without ssh in the first place)

**Comment by Rabenherz112** [comment]
That would be awesome!
While the user can still utilize SSH to manage their server, my concern lies in the current usage of the "ubuntu" username and recommendation to use the Ubuntu operating system in your instructions. This poses an issue as bots often attempt common usernames during automated attacks.

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> That would be awesome! While the user can still utilize SSH to manage their server, my concern lies in the current usage of the "ubuntu" username and recommendation to use the Ubuntu operating system in your instructions. This poses an issue as bots often attempt common usernames during automated attacks.

I updated the readme to provide a safer ssh config, the user "ubuntu" is a legacy from when I started the project... this is the default user in aws https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/managing-users.html when you spin an instance (ssh is already configured to only accept key pairs though)

Another thing I could do (and it is in the todo list) is changing the user ubuntu to a variable.

I will try a local deployment on the target machine first as this remove ssh altogether (assuming the user have another way to connect)

**Comment by nodiscc** [comment]
Is the Flask app able to run commands as root with `sudo` without a password? https://github.com/ba9f11ecc3497d9993b933fdc2bd61e5/temporary.chat-playbook/blob/master/roles/chat_server/files/app/app.py.j2#L180

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> Is the Flask app able to run commands as root with `sudo` without a password? https://github.com/ba9f11ecc3497d9993b933fdc2bd61e5/temporary.chat-playbook/blob/master/roles/chat_server/files/app/app.py.j2#L180

yes, 2 commands exactly.

see here : https://github.com/ba9f11ecc3497d9993b933fdc2bd61e5/temporary.chat-playbook/blob/master/roles/chat_server/files/sudoers/sudoers.j2

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
> > That would be awesome! While the user can still utilize SSH to manage their server, my concern lies in the current usage of the "ubuntu" username and recommendation to use the Ubuntu operating system in your instructions. This poses an issue as bots often attempt common usernames during automated attacks.
> 
> I updated the readme to provide a safer ssh config, the user "ubuntu" is a legacy from when I started the project... this is the default user in aws https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/managing-users.html when you spin an instance (ssh is already configured to only accept key pairs though)
> 
> Another thing I could do (and it is in the todo list) is changing the user ubuntu to a variable.
> 
> I will try a local deployment on the target machine first as this remove ssh altogether (assuming the user have another way to connect)

I created a new branch and was able to deploy sucessfully without a deployment machine (self contained deployment). I will run some more tests with all the use cases, and update the relevant documentation, but this could become the favorite way to deploy, thanks for your inputs!

**Comment by nodiscc** [comment]
Since we are talking about this, I find the code extremely hard to browse/audit because the deployment tooling is not separated from the app, and the application code is buried deep in https://github.com/ba9f11ecc3497d9993b933fdc2bd61e5/temporary.chat-playbook/tree/master/roles/chat_server/files/app. While I have nothing against the deployment method (ansible is my tool of choice), I suggest clearly separating the application files from the deployment tooling (e.g. store the code in `src/`, and use `git` and `copy` modules ot install it).

Templating shell scripts directly is also discouraged, use an external, templated configuration file and `source` it instead. 

> Is the Flask app able to run commands as root with sudo without a password?
>> yes, 2 commands exactly.

Command injection is still probably possible, because those scripts accept user-provided arguments. I did not check in detail. Anyway, a web application with `sudo` access is a huge red flag for me.

No offense, this application looks useful, but in a very early "prototype" stage, with confusing codebase, very minimal documentation, no static analysis/linting/CI (`shellcheck` and `asnible-lint` come to mind), not very useful commit messages/git history, almost no comments, incomplete installation docs, hardcoded SSH username, use of deprecated ansible modules... There are no quality requirements for a project to be added to the list, but I know I would definitely **not** run this in a production-like setup exposed to the Internet in the current state. Which is why I will not approve this PR, this project needs to mature quite a bit.

About the documentation, I suggest writing a clean, step-by-step guide that a user can follow as if they just got a shell on a fresh VPS/VM.

**Pull request closed without merging**
