### PR TITLE
Remove tagtool - it's no longer maintained

### PR DESCRIPTION
**Pull request by miloskroulik**
Last release of https://gitlab.com/tagtool/tagtool was more than year ago, also website doesn't work (it has been replaced by some splash screen). This is no longer awesome.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [ ] Your additions are ordered alphabetically.
- [ ] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [ ] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [ ] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [ ] Your additions have their `License` and main server-side `Language`/platform/requirement listed.
- [ ] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [ ] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is "Add aaa to bbb" for adding software aaa to section bbb. Do not call it "Update README.md".

### CODE REVIEW

**Review by nodiscc — APPROVED** [review]
Thanks

**Comment by robsdedude** [comment]
As a maintainer, I can say it is maintained. There are just no issues. It is in a rather finished state. The splash screen on the website is for potential B2B customers.

**Comment by fidergo-stephane-gourichon** [comment]
Hi, just passing by.

> The landingpage on the website is for potential B2B customers.

Is that it?

> "Interested in trying out TagTool?
> Leave us your email.
> We'll contact you soon. "

No info? Nothing about what this is about?
To me, the message it conveys is: "we have an idea to get money, may have written a line or code or not, maybe the idea is only to harvest e-mails, and it this is enough to let us spam you, feel free to give us your e-mail that is valuable to us". Sorry if feels "direct" consider it feedback from a neutral visitor given the general state of the Internet.

From the PR I see https://gitlab.com/tagtool/tagtool notice that it says "Demo screenshot" which is a broken link.

There is a shouting "demo" link that requires a password.

All in all I read some text, cannot see a screenshot.
The product might be awesome, but the publicly easily visible material, is it?

Feel free to fix all this and make the whole thing awesome!

**Comment by robsdedude** [comment]
I also noticed the broken demo image. Seems like gitlab changed the handling of relative links. I just fixed that. Thanks for letting me know. And the demo requires a password to demonstrate the option for a password. The password hint right above the password field tells you what password to enter.

Thank you very much for your feedback.

**Comment by nodiscc** [comment]
@miloskroulik @robsdedude @fidergo-stephane-gourichon so should this be reverted?

**Comment by miloskroulik** [comment]
I'm not sure what the policies regarding this are, but [commit history](https://gitlab.com/tagtool/tagtool/-/commits/master) doesn't look that awesome to me. If @robsdedude says it's finished, this probably means it no longer gets security updates - this should be probably explicitly mentioned, if this is reverted.

**Comment by nodiscc** [comment]
Regardless of functional status (it might well be fature-complete and no longer needs any kind of development), it looks like there is no maintenance on the project at all. @robsdedude I suggest that you run something like https://github.com/aquasecurity/trivy to estimate what needs to be done security-wise.

**Pull request merged**
