### PR TITLE
flatten table of contents + syntax and case fixes

### PR DESCRIPTION
**Pull request by nodiscc**
* fix TileServer PHP and 0bin syntax
* fix OwnTracks Recorder syntax/language tag
* standardize OCaml case - https://en.wikipedia.org/wiki/OCaml
* rename Homer to SIPCAPTURE Home (offical name) - Homer already exists in Homepages
* standardize Nodejs case, don't repeat Nodejs in descriptions
* reorganize TOC/scetion titles: move all list sections to level 3, don't nest sections/subsections, use Title Case everywhere
* in preparation for https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1038

### CODE REVIEW

**Comment by nodiscc** [comment]
https://github.com/awesome-selfhosted/awesome-selfhosted/blob/dbc5d796dab5526ec64e09a521770a23ef9bb728/README.md looks fine

**Comment by n8225** [comment]
Is there a reason for sentence case for the titles? I think title case would look better and would be more fitting. Other than that I didn't see any issues.

**Comment by slel** [comment]
Using sentence case for all document titles and headers comes
recommended by several code style guidelines including Google's:
https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings

**Review by n8225 — APPROVED** [review]

**Comment by nodiscc** [comment]
I Think Title Case is Hard to Read. There are no clear conventions on what words should be capitalized. Wikipedia uses sentence case for section titles. Anyway I reverted this change, we can have another look later.

**Comment by n8225** [comment]
I'm using to seeing title case for titles, so I don't have issues reading . After some research I am now aware most newer style guides are pushing sentence case for titles. As long as it's consistent either would be fine.

**Review by nodiscc — COMMENTED** [review]
Fixed, rebased, added minor syntax/wording fixes

**Pull request merged**
