### PR TITLE
Remove firefox send from section peer to peer filesharing. 

### PR DESCRIPTION
**Pull request by kokomo123**
Firefox Send was discontinued today due to financial problems and such. Hence, hopefully this can be removed so people don't get confused. https://techcrunch.com/2020/09/17/mozilla-shutters-firefox-send-and-notes/. Thanks!

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [ ] Your additions are ordered alphabetically.
- [ ] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [ ] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [ ] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [ ] Your additions have their `License` and main server-side `Language`/platform/requirement listed.
- [ ] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [ ] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is "Add aaa to bbb" for adding software aaa to section bbb. Do not call it "Update README.md".

### CODE REVIEW

**Comment by CatTheHacker** [comment]
[Firefox Send](https://github.com/firefox/send) had last commit 3 days ago. While Mozilla discontinued Firefox Send service, the software is still great option for people to self-host and imo I wouldn't remove it (yet).

**Comment by kokomo123** [comment]
As per the comments of CatTheHacker, and my awareness not to read contributing.md, failed me. I shall wait to remove this from the list in 6-12 months or unless you guys deem it abandoned right now. Feel free to reopen this PR when the time comes. Thanks.

**Comment by nodiscc** [comment]
@CatTheHacker @kokomo123 https://github.com/mozilla/send is now archived, that means it can reasonably be removed as no one will work on it in the future. We shouldn't encourage installing something that will never ever get any kind of maintenance. If you have it installed now it's a good idea to think about possible migration plans.

If a good fork re-emerges we can add it instead. Can you re-send the patch to remove FF Send?

**Comment by kokomo123** [comment]
Yup! Gonna do that now. @nodiscc #2231 is now open. New to github so don't know how to attach a new repo to this.

**Pull request closed without merging**
