### PR TITLE
Add "Resume Builders" Section, Add "Reactive Resume"

### PR DESCRIPTION
**Pull request by AmruthPillai**
### Resolves Issue #2036 

> - Add New Section under "List of Software": **Resume Builders**
> - Add Project: [**Reactive Resume**](https://github.com/AmruthPillai/Reactive-Resume)

---

```markdown
## Resume Builders

- [Reactive Resume](http://docs.rxresu.me/) - A one-of-a-kind resume builder that keeps your privacy in mind. Completely secure, customizable, portable, open-source and free forever. ([Demo](http://rxresu.me/), [Source Code](https://github.com/AmruthPillai/Reactive-Resume)) `MIT` `Javascript`
```

---

## Resume Builders

- [Reactive Resume](http://docs.rxresu.me/) - A one-of-a-kind resume builder that keeps your privacy in mind. Completely secure, customizable, portable, open-source and free forever. ([Demo](http://rxresu.me/), [Source Code](https://github.com/AmruthPillai/Reactive-Resume)) `MIT` `Javascript`

### CODE REVIEW

**Comment by AmruthPillai** [comment]
Ah, sorry. Didn't read the fine print there about having min. 3 projects. I've readded it to Misc/Other. Somehow I feel it doesn't fit in with the other CMS options.

**Comment by AmruthPillai** [comment]
@nodiscc Is this okay to be merged now?

**Comment by AmruthPillai** [comment]
No, no. It is not a Node.js app. It is a browser-based React app, so keeping it as Javascript would be the right thing to do. And Docker, not really the main selling point here as people could host the site however they wish. The app doesn't depend on Docker. Javascript/React would be the right tag for it.

**Comment by nodiscc** [comment]
The right question is, what do you need server-side to provide the service?

Can I host it without Docker?
 - If no -> `Docker`
 - If yes, where can I find the install procedure?
 - If yes, does it require npm/node server-side?
   - If yes -> `Nodejs`. Even if not, if it can only be built using node, it's fine to tag it `Nodejs`
   - If no, it's a static html5/css/js app, and the only requirement is a browser with JS support -> `Javascript`

I wish this could be made more explicit in CONTRIBUTING.md or the Pull Request template (which you didn't keep in your PR :), but it's still not clear about this), but didn't find time

Thanks

**Comment by AmruthPillai** [comment]
Understood :) I've changed it to `Docker/Nodejs` now.

**Pull request merged**
