### PR TITLE
Add Input-Leap to Automation

### LINKED ISSUE #3327: barrier KVM solution
https://github.com/debauchee/barrier

for using a single keyboard/mouse with as many computers as you want. Main machine hosts other machines connect can move mouse across the different machines as if they were just multi monitors

### PR DESCRIPTION
**Pull request by kokomo123**
This should close #3327. I believe Barrier would fit well in Automation and I think this is all that is needed. 
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by kokomo123** [comment]
Perhaps I uncheck actively maintained but this is in a usable state as a software to be put on the list. Not sure though, feel free to correct me if i'm wrong anyone.

**Comment by nodiscc** [comment]
It seems barrier has not seen much maintenance for a while: https://github.com/debauchee/barrier/commits/master

I would like to add it since it's the only software in its "category", and it's packaged in Debian stable; but judging by the number of untriaged issues, and the fact that it is marked for removal from Debian [[1]](https://tracker.debian.org/pkg/barrier) [[2]](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020987), I'd rather wait for other advice.

@debauchee @walker0643 is barrier still maintained?

Edit: I just saw https://github.com/input-leap/input-leap/issues/1414 which hints at a better maintained fork (?)

**Comment by kokomo123** [comment]
Let me then change the repository over to that. Seems fitting 👍🏻 @nodiscc

**Comment by kokomo123** [comment]
Bump on this PR!

**Comment by nodiscc** [comment]
Sorry for the delay; I'm not sure this is suitable yet - installation instructions are not working.

The README points to https://github.com/input-leap/input-leap/releases but there are no releases yet. Input-leap is not packaged in distribution repositories either (while Barrier was, but it's no longer maintained).

@p12tic are there plans for a new release of input-leap? It is ~1000 commits ahead of barrier but there is currently no way to install it as described in the docs.

**Comment by kokomo123** [comment]
I see what you mean as the milestone for making such a release hasnt had any progress on it just yet. This one's tough to gauge.

**Comment by p12tic** [comment]
@nodiscc My current personal estimate is end of year.

**Comment by kokomo123** [comment]
I suppose we should close this PR and revisit at another time then, oops!

**Comment by nodiscc** [comment]
Thanks for your help sorting this out @kokomo123 , I would very much like to see this added in the future, I have used the old fork in the past (then called Synapse which is now proprietary) and it was useful.

**Pull request closed without merging**
