### PR TITLE
Rename FreeNAS to TrueNAS CORE

### PR DESCRIPTION
**Pull request by FabioLolix**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of
  - [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management),
  - [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics),
  - [staticgen.com](https://www.staticgen.com/)
  - [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] The `Language` tag is the main server-side requirement for the software - don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

Hello, recently FreeNAS has been renamed/rebranded as TrueNAS CORE

I have kept https://github.com/freenas/freenas for source code because at https://github.com/truenas is developed TrueNAS SCALE which is based on Debian instead of FreeBSD

### CODE REVIEW

**Comment by nodiscc** [comment]
I don't Think TrueNAS is Free software anymore: https://github.com/freenas/freenas/blob/master/src/freenas/usr/local/share/truenas/eula.html#L64:

> TrueNAS Software is only authorized for use with a TrueNAS Device identified by a specific  
> strictly prohibits the acts of decompiling, reverse engineering, or disassembly of the Product, including TrueNAS Software

It would mean we have to remove it from the list (move it to non-free.md)

**Comment by FabioLolix** [comment]
I'll go out in minutes but I'll check it, the "TrueNAS CORE" is free to use but I'll investigate

**Review by nodiscc — CHANGES_REQUESTED** [review]
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2364#issuecomment-757494877 if TrueNAS CORE is now non-free; it must me moved to non-free.md

**Comment by nodiscc** [comment]
ping @FabioLolix

**Comment by FabioLolix** [comment]
TrueNAS CORE is still open source and free to use

truenas
truenas2
truenas3


> I don't Think TrueNAS is Free software anymore: https://github.com/freenas/freenas/blob/master/src/freenas/usr/local/share/truenas/eula.html#L64:
> 
> > TrueNAS Software is only authorized for use with a TrueNAS Device identified by a specific
> > strictly prohibits the acts of decompiling, reverse engineering, or disassembly of the Product, including TrueNAS Software

That is for sure for their "TrueNAS Enterprise" offering which is bundled with their hardware that they are selling

**Review by subnut — APPROVED** [review]
Of the whole TrueNAS offerings, only __TrueNAS Core__ is Open-Source. It ***is*** the equivalent of FreeNAS.

**Comment by nodiscc** [comment]
> TrueNAS Core is Open-Source

Where is the license for TrueNAS Core?

**Comment by subnut** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/TrueNAS) -

> TrueNAS is the branding for a range of free and open-source network-attached storage (NAS) operating systems produced by ixSystems, and based on FreeBSD and Linux, using the OpenZFS file system. It is licensed under the terms of the BSD License and runs on commodity x86-64 hardware.

**Comment by nodiscc** [comment]
I'm sorry, I couldn't find any information in TrueNAS source code on what the license actually is, except the EULA I linked earlier. The license must be provided with the source code, especilly if the license is really BSD](https://opensource.org/licenses/BSD-3-Clause)

> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

Since this is the oldest open pull request here, I will now close it and open a new one to remove FreeNAS/TrueNAS until the license situation is clarified.

**Pull request closed without merging**
