### PR TITLE
Add Rukovoditel to Software Development - Project Management

### LINKED ISSUE #2678: New entry: Rukovoditel
Hello.
I know about the project management system Rukovoditel written in PHP.
It is worth to tak it into the list.
https://www.rukovoditel.net/
Best Regards
Eberhard

### PR DESCRIPTION
**Pull request by confused-Techie**
Resolves #2678

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by arfahmd** [comment]
thanks

**Review by nodiscc — COMMENTED** [review]
Where is the source code? (preferably a git/version control repository)

**Comment by mzch** [comment]
The developers publish .zip file only, perhaps no public repository. We can get source code .zip file from https://www.rukovoditel.net/download.php

**Comment by confused-Techie** [comment]
I've committed 614bdbd89eb0aa4408021c63a1fb303c991316f7 to my fork to include the Source Code Download Page the was provided by @mzch since they don't seem to have an available web version of their source.

**Review by Rabenherz112 — COMMENTED** [review]
I tried using your Demo. However, when using the Link you provided in your pull request, I can't access it.
> [Demo](https://demoen.rukovoditel.space/index.php?module=users/login)

**Comment by confused-Techie** [comment]
> I tried using your Demo. However, when using the Link you provided in your pull request, I can't access it.
> 
> > [Demo](https://demoen.rukovoditel.space/index.php?module=users/login)

Looks like, as I originally published this about 2 years ago, they have now removed the publicly accessible demo.

Now all I'm able to find is the ability to [request a demo](https://www.rukovoditel.net/demo.php) on their website. So unfortunately that may not be possible to easily link to. Would we think it's best to remove the demo line completely? Or rather link to the page to request a demo?

**Comment by Rabenherz112** [comment]
Hmm, not sure either. I would probably be for not including the Link to that "Demo" since you now have to register an Account there to check it out.
Maybe @nodiscc could say something about what he thinks about this.

**Comment by confused-Techie** [comment]
Alright @Rabenherz112 based on your suggestion I've removed the demo link.

**Review by Rabenherz112 — APPROVED** [review]

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
