### PR TITLE
Link Clean Up

### LINKED ISSUE #2790: Broken links, dead projects
"Drive Virtual" - abandoned domain
"Resilio Sync" - doesn't link downloadable software
"Dropcenter" - abandoned project, no download to be found
"Koken" - abandoned project
"Active Collab" - not self-hosted anymore

 on https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md

### LINKED ISSUE #2793: Blogging platforms: Lots of CMSes listed there
Blogging platform usually means support for blogging things like remote publishing via XML-RPC / MetaWeblog / AtomPub, or sending and/or receiving of pingbacks and trackbacks.

Many of the entries under "Blogging platforms" lack all of the above and thus are CMSes, not blogging platforms.

### PR DESCRIPTION
**Pull request by KieranRobson**
Looked through blogging platforms for sneaky CMS and updated as accordingly.
- Closes #2793 
- Closes #2790 

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by KieranRobson** [comment]
On a side note, ran linter on `non-free.md` too with no issues 
#2790 could be closed

**Review by kokomo123 — APPROVED** [review]
Looking good! Thanks for clearing it up. Those projects shall be missed.

**Comment by KieranRobson** [comment]
```
Issues :-(
> Links
  1. [L0208] 503 https://git.dotclear.org/dev/dotclear
  2. [L0770] 401 https://demoshop.oxid-esales.com/community-edition/
  3. [L0848]  https://pydio.com/ SSL_connect returned=1 errno=0 peeraddr=62.210.6.224:443 state=error: certificate verify failed (unable to get local issuer certificate)
  4. [L1823]  https://www.taskfreak.com/original SSL_connect returned=1 errno=0 peeraddr=198.54.114.183:443 state=error: certificate verify failed (certificate has expired)
> Dupes
  None ✓```
  
  After running more awesome bots - Have widdled down the issues to the above - all links works but may be unsecure or require login

**Review by nodiscc — APPROVED** [review]
thank you

**Pull request merged**
