### PR TITLE
Add vabene1111/recipes 

### PR DESCRIPTION
**Pull request by D0T1X**
I just found this program through a conversation on reddit with the dev of it and i think it really deserves a spot here.
I'm also right now talking to the dev for some changes and translations to add.

### CODE REVIEW

**Comment by Tzahi12345** [comment]
You should probably update the title to follow the format of the other issues made (ex. "Add Recipes"). Looks like a cool app though!

**Comment by D0T1X** [comment]
Yes I totally agree there with you. I just committed the pull and saw I fucked up on that one. But can't seem to find how to change the title, just the body of the request. I'm quite new to fit so I'm sorry if I don't understand everything yet and fuck up something like here.

**Comment by Tzahi12345** [comment]
Haha should be an easy fix, there should be an edit button on this page, right near the title.

**Comment by D0T1X** [comment]
Thanks @Tzahi12345 i just woke up so checked on my phone. aparently the edit for the title is only availble on the desktop. HAve changed it for you know. hope this is better.

**Comment by Tzahi12345** [comment]
Quick note, approved != merged, pretty sure you need to keep it open so they can merge it into master

**Comment by D0T1X** [comment]
Ah thanks again, I thought everything was done. 

Then why would you approve something but not merge it?

**Comment by Tzahi12345** [comment]
>Ah thanks again, I thought everything was done.

No problem, this system is pretty confusing for starters, didn't want to see your PR never get merged because of something that silly.

>Then why would you approve something but not merge it? As in that function being present.

Maybe as like a first check, then someone higher up merges? No clue honestly.

**Pull request merged**
