### PR TITLE
Add Forgejo to Software Development - Project Management

### PR DESCRIPTION
**Pull request by DIWesser**
Add Forgejo, a recent committee run fork of Gitea by a team of original Gitea maintainers after the Gitea project ownership was transferred to a for-profit company. For more information, see the [Forgejo FAQ](https://forgejo.org/faq/).

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Review by kokomo123 — COMMENTED** [review]
I believe I can validate this one to be added to the self hosted list. It's being actively added to with new features coming. A stable release is in the works as they are actively moving away from having gitea branding to their own / releasing docker containers / releasing a docker compose file in the future perhaps as well. I have not explicitly approved it as I'm waiting for nodiscc / others for their opinion before making a approving review.

**Review by kokomo123 — APPROVED** [review]
Approving it now as I feel like it's a right call to get this onto the list as there is a stable release, and it's been pushing commits.

**Comment by kokomo123** [comment]
Bump @nodiscc

**Comment by nodiscc** [comment]
What does this fork improve over the upstream Gitea?

**Comment by kokomo123** [comment]
> What improvements does this fork provide compared to the upstream Gitea?
> 
> Edit:
> 
> > the domains and trademark of Gitea were transferred to a for-profit company without knowledge or approval of the community
> 
> The domain name and trademarks were previously owned by a single individual, not by the community. I don't see anything in https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#owners that makes this move illegitimate. As far as I know Gitea is still a community project with a process to elect owners.
> 
> This fork is based on the assumption that Gitea will switch to a "freemium" distribution model, which so far has not happened. (I agree the change in domain name/trademark ownership should have been handled more transparently). Unless that happens, or the fork starts to diverge significantly from upstream, I see no point in adding it to the list.

I can see your point in not affecting Gitea as a whole, but let me link you some blog posts referring to what has happened to it. https://blog.codeberg.org/codeberg-launches-forgejo.html,  https://forgejo.org/2022-12-15-hello-forgejo/. I'm not a contributor or anything, and im sure they can explain more about what makes Forgejo, forgejo but I can see they give more transparency and want the community to get involved in its governance more then anything along with helping out Gitea by making it a soft fork. I think it will eventually diverge from Gitea but it's actively cherrypicking and adding its own commits regarding accessibility, and federation. That's my take on it. They also don't use github for issues, rather relying on Codeberg's instance of Forgejo for everything along with matrix and woodpecker CI instead of Drone. But as you said, we could put this on hold for now.

**Comment by wxiaoguang** [comment]
I have contributed a lot to Gitea and have experienced the `soft-fork` event.

I think some information is not accurate here.

So I'd like to clarify them from my view:


> > adding its own commits regarding accessibility, privacy, and federation
> 
> We originally intended to [implement Federation in Gitea](https://nlnet.nl/project/Federated-Gitea/). Then [Gitea Ltd. happened](https://blog.gitea.io/2022/10/open-source-sustainment-and-the-future-of-gitea/) out of a sudden which broke the trust from parts of the community. Forgejo is our answer to this move after an [Open Letter](https://gitea-open-letter.coding.social/) was unanswered.

At the moment, Forgejo is a 100% totally soft-fork of Gitea. There is almost no different on accessibility / privacy.

About the federation: Forgejo is working on it but at the moment, all federation related code are all from Gitea. Maybe in the future Forgejo could do better for federation, but not now. 


And about Gitea Ltd, I do not know how Forgejo people think, but I guess there is no much different sooner or later. 
[Declare Easter-Egg as a group of interest in Forgejo](https://codeberg.org/forgejo/meta/pulls/180)

> I know that many Forgejo people criticized Gitea Ltd.
> Now I guess Forgejo is heavily controlled by Easter-Egg.

**Comment by mzch** [comment]
I think the relationship between Gitea and Forgejo is simlar to the relationship betwenn MySQL and MariaDB. At first MariaDB was a soft-fork of MySQL but developers knew MariaDB was different from MySQL as an independent product. I beleive Forjoge is in the same situation.

**Comment by wxiaoguang** [comment]
> I think the relationship between Gitea and Forgejo is simlar to the relationship betwenn MySQL and MariaDB. At first MariaDB was a soft-fork of MySQL but developers knew MariaDB was different from MySQL as an independent product. I beleive Forjoge is in the same situation.

To be honest, at the moment and in the foreseeable future, I do not think so. Oracle wanted to "hide" MySQL and developed slowly, so MySQL core developers started MariaDB, MariaDB succeeded.

For Gitea, almost all core developers are still on Gitea, Gitea is still developing rapidly, almost all new features/enhances/bug-fixes are done by Gitea side. The commit history can be used a reference.

**Comment by nodiscc** [comment]
The MySQL/MariaDB case is different (you can look it up, an interesting bit is the discussion that led to the replacement of MySQL with MariaDB in Debian).

This fork is born out of political/leadership concerns over elected owners allegedly having too much "control" over the project. I agree that such issues are important. But there is no evidence of Gitea maintainers harming their users (aside from clumsy management of the trademark ownership transfer) or crippling the software for commercial purposes.

Here is an example of a project actively engaging in harmful behavior, that was replaced by a fork: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3609

If we started accepting adding forks which only bring owner/leadership changes, nothing would prevent a malicious contributor, from forking 50 projects on this list, and requesting their forks to be added under the pretext that they don't like how previous owners manage the project, effectively decreasing the usefulness/readability of the list (it's already quite large and cluttered).

> I think it will eventually diverge from Gitea

@Ryuno-Ki Is there a table that lists **differences between Gitea and Forgejo, feature-wise**? Gitea has one at https://docs.gitea.io/en-us/installation/comparison/ which compares it against the original Gogs project. This is actually helpful for users trying to choose a fork. I think Forgejo should maintain a similar document, else there is no actual reason to pick it over Gitea, or to list it here.

**Comment by Ryuno-Ki** [comment]
> I also don't believe Ryuno-Ki is apart of Forgejo any longer due to some disputes.

[Not by choice.](https://jaenis.ch/blog/2023/forgejo-sacrifice-inclusiveness-and-calls-it-healing/)

Since moving to Debian I have Go v1.19 and can't contribute to Forgejo. I still observe and read the messages around it.

**Comment by caesar** [comment]
I think just the fact that Codeberg is supporting and has switched to Forgejo probably makes it notable enough to be included. It's more actively developed than many other projects on the list.

**Comment by nodiscc** [comment]
The problem is not specifically about Forgejo, but about adding forks to the list that only change leadership/project governance (see my previous comment).

**Comment by caesar** [comment]
I understand that, but I guess it's a question of where you draw the line once a fork becomes significant enough in its own right. For example, Gogs and Gitea are both on the list, even though Gitea was also a fork "that only change[d] leadership/project governance" (more so than Forgejo tbh). Similarly, ownCloud and Nextcloud are both on the list despite the same originally applying.

Referring to your previous comment, I think it's clear that "forking 50 projects on this list, and requesting their forks to be added under the pretext that they don't like how previous owners manage the project" is not the case with Forgejo. It's just a case of where you do want to draw that line I guess, and I think it will always have to be a case-by-case decision, meaning the decision *is* specifically about Forgejo.

My own opinion is that even if you personally don't support the goals of Forgejo, keeping it off the list makes the list less useful. But that's just my two cents. 😀

**Comment by nodiscc** [comment]
> Gitea was also a fork "that only change[d] leadership/project governance".

In its early stages when it was "just" another Gogs fork, I would have voiced the same concerns about adding Gitea. This is no longer the case, for a while now Gitea has significantly diverged from Gogs in terms of implementation and features. [This page](https://docs.gitea.com/next/installation/comparison) clearly shows in which ways.

The same can be said about Nextcloud/Owncloud [[1]](https://nextcloud.com/compare/) [[2]](https://owncloud.com/compare-filesharing/owncloud-vs-nextcloud/)

It was asked multiple times if someone could point to a similar document for Forgejo (even non-official), but it was never provided.

> the decision is specifically about Forgejo

You can [search](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls?q=is%3Apr+fork+is%3Aclosed+label%3Aaddition) other issues/PRs and see for yourself that requests to add forks all receive the same scrutiny - the submitter is asked to explain differences between their fork and the parent project (which they actually do, while in 6 months since this PR was opened, noone has provided this info, except "different project owners").

> It's just a case of where you do want to draw that line I guess

You are right that a line has to be drawn somewhere. In the future, we could add a contribution guideline along the lines of `If the project you are adding is forked from another project already listed here, please provide a clear list of differences between both`.

> [...] requesting their forks to be added under the pretext that they don't like how previous owners manage the project" is not the case with Forgejo. 

Please provide proof to the contrary, and I will gladly approve this PR then.

**Comment by nodiscc** [comment]
> In the future, we could add a contribution guideline along the lines of `If the project you are adding is forked from another project already listed here, please provide a clear list of differences between both.`

Done https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3998

> If you are adding software forked from another project, please provide/link to a clear list of differences between both.

I will leave this open for some time in case someone wants to provide this information (I could not find it anywhere after a thorough search).

**Comment by caesar** [comment]
I think it's fair to say that if you want to discount the ownership / development model (which was the original primary motivation for the fork, and from what I've seen is a meaningful difference on its own for many people), the actual functional differences at this stage are still minimal, so if that is your criterion I'm guessing you won't want to add Forgejo yet.
In particular, the goal of Forgejo is to contribute as many changes as possible upstream, and therefore actually to keep the differences minimal at least in the short term.

That said – and as you rightly point out, in the absence of an actual document listing the differences – I think the main non-organisational differences so far are:
- a somewhat different Actions architecture
- some different defaults, in particular relating to privacy-by-default
- different default themes

There are also some changes already in the development branch but not yet released, including some federation features (the F3 driver).

And there are more features still in development but that won't make it out for at least another few months, including more federation features and a full UI rewrite.

Bearing all that in mind, perhaps you'd rather come back to this in a few months' time?

(Note: I've been involved in Forgejo but haven't been one of the primary contributors, so what I say above about features is not authoritative.)

**Comment by caesar** [comment]
Oh I forgot (reminded by reviewing the [release notes for v1.20](https://codeberg.org/forgejo/forgejo/src/branch/forgejo/RELEASE-NOTES.md#draft-1-20-0-0): Forgejo also has [some moderation features](https://forgejo.org/docs/v1.20/user/blocking-user/) that are not part of Gitea.

**Comment by nodiscc** [comment]
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.

**Pull request closed without merging**
