### PR TITLE
remove Croodle (unmaintained since 2021)

### PR DESCRIPTION
**Pull request by nodiscc**
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3558
- `WARNING:awesome_lint.py: Croodle: last updated -731 days, 1:27:15.139038 ago, older than 365 days`

### CODE REVIEW

**Comment by nodiscc** [comment]
@jelhan is https://github.com/jelhan/croodle still maintained and working?

**Comment by nodiscc** [comment]
Quoting reply from https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2266#issuecomment-1407399462

> I wouldn't consider it dead. Still planning to do a major revamp. But haven't found the time doing so in last years. And not sure if I will find this year to be honest.

Putting this on hold.

**Comment by jelhan** [comment]
There is at least one running instance of Croodle, which I'm aware of: https://www.systemli.org/poll/

**Comment by nodiscc** [comment]
Moved to https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3927

**Pull request closed without merging**
