### PR TITLE
Added My Dash to Personal Dashboards

### PR DESCRIPTION
**Pull request by krestaino**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements:
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), including closed ones.
- [x] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by krestaino** [comment]
Let me know if this project feels more relevant over at https://github.com/n1trux/awesome-sysadmin.

**Comment by nodiscc** [comment]
Hi @krestaino, thanks for the patch, I would prefer the following:
 - On top of the `Personal dashboards` section, remove the link to the `#monitoring` section, and  add the text `See https://github.com/n1trux/awesome-sysadmin#monitoring and https://github.com/n1trux/awesome-sysadmin#metric--metric-collection`
- Remove the https://github.com/Kickball/awesome-selfhosted#monitoring section (only `Personal dashboards` links to it.
- Add my-dash to https://github.com/n1trux/awesome-sysadmin#metric--metric-collection (`Dashboards` subsection). The reason for this it's that it more a monitoring dashboard for servers/network services, I think awesome-sysadmin is a better fit.

Do you agree?

**Comment by nodiscc** [comment]
@krestaino ping, do you want to work on the changes I suggested above?

**Comment by nodiscc** [comment]
No reply, closing.

**Pull request closed without merging**
