### PR TITLE
Remove email

### PR DESCRIPTION
**Pull request by Pernat1y**
Why the f**k do you even keep emails in plain text like this?!

### CODE REVIEW

**Comment by jnwatts** [comment]
This change won't solve your problem, see
https://github.com/awesome-selfhosted/awesome-selfhosted/blob/6fd222b250a4ea20813f69d9dcc1cdf7e571ab72/Makefile#L36

**Comment by Pernat1y** [comment]
Thanks to pointing it out.
Should I update the script to 'grep -v' myself out of that list or what?

**Comment by nodiscc** [comment]
see https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2580

> keep emails in plain text like this

you did this yourself when you sent commits with your e-mail set in `git config user.email`. Spambots will read the git log anyway

> Should I update the script to 'grep -v' myself out

you can add an entry in https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/.mailmap

**Comment by nodiscc** [comment]
See also https://gitlab.com/gitlab-org/gitlab/-/issues/20960 on the topic of `git log` and GDPR compliance

**Comment by Pernat1y** [comment]
The thing is, if you google my email, the only results you will get are some sorts of forks/clones of this exact repository. And this is not the only repo I made commits to. Got the idea?
Sorry for the aggressive tone, but this is just bad practice.

**Comment by nodiscc** [comment]
> if you google my email, the only results you will get are some sorts of forks/clones of this exact repository

You're only making it worse...

image

> this is not the only repo I made commits to. Got the idea?

Well I understand it's a personal SEO problem. I contribute to other projects as well and this is the one that comes up in google results. Either contact google to request removal of those search results, or update https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/.mailmap as I suggested.

> but this is just bad practice.

Maybe you shouldn't commit using an email address you don't want published?

**Comment by pengc99** [comment]
here is my git anonymized address: pengc99@users.noreply.github.com, i just updated my git preferences and cli to use this address.

**Pull request closed without merging**
