### PR TITLE
Add Umbrel in Self-hosting Solutions

### PR DESCRIPTION
**Pull request by AuHau**
I am not sure about the license. They are using a "proprietary" license that is very similar to Open Source licenses (in the end everything is allowed except commercial usage is allowed). See here: https://github.com/getumbrel/umbrel/blob/master/LICENSE.md

Please advise.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by nerrixDE** [comment]
@runical is a FOSS (and more advanced) fork. Would be better suited for this list imo.

cc @aarondewes

**Comment by AaronDewes** [comment]
As another note on Umbrel, parts of it's code have no license, so they don't allow any forks, other parts are entirely closed source.

**Comment by AuHau** [comment]
Interesting did not know about Citadel nor about Umbrel's license issues. Is Citadel Umbrel's fork? It looks very similar (from the dashboard POV), but then based on @AaronDewes comment isn't forking Umbrel not allowed?

**Comment by AaronDewes** [comment]
Citadel's dashboard is currently a fork of Umbrel's non-free dashboard, which allows noncommercial forks. Everything else has been rewritten, and the dashboard will also be replaced soon.

**Comment by AuHau** [comment]
Interesting info, thanks!

**Comment by AuHau** [comment]
Do you plan to keep compatibility with their App Store?

**Review by nodiscc — CHANGES_REQUESTED** [review]
> everything is allowed except commercial usage

Then it must go to `non-free.md`

**Comment by nodiscc** [comment]
No reply for a month, closing

**Pull request closed without merging**
