### PR TITLE
Add Webiny to Content Management Systems (CMS)

### PR DESCRIPTION
**Pull request by swapnilmmane**
[Webiny](https://www.webiny.com) is Open-Source Serverless Enterprise CMS, added it to the CMS sections, thank you!

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Comment by swapnilmmane** [comment]
Hi @nodiscc, thank you for reviewing the pull request. 
Please let me know if you need any additional information from me, thank you!

**Review by nodiscc — COMMENTED** [review]
> Deploys to AWS.

How do I host this on my own server?

**Comment by swapnilmmane** [comment]
Hi @nodiscc, thanks for looking into the pull request.

Regarding, 
> How do I host this on my own server? 

Webiny is an open-source serverless CMS, here is a [guide to deploying Webiny to AWS](https://www.webiny.com/docs/get-started/install-webiny). 

As I mentioned, it is having serverless architecture, so it deploys everything to AWS and uses AWS serverless services like Lambda, DynomoDB, S3, CloudFront, etc. 

Please let me know if you need any further details, will be happy to assist you, thank you!

**Comment by nodiscc** [comment]
> it deploys everything to AWS and uses AWS serverless services like Lambda, DynamoDB, S3, CloudFront, etc

https://github.com/awesome-selfhosted/awesome-selfhosted#awesome-selfhosted:
> This is a list of [Free](https://en.wikipedia.org/wiki/Free_software) Software [network services](https://en.wikipedia.org/wiki/Network_service) and [web applications](https://en.wikipedia.org/wiki/Web_application) which can be hosted on your own server(s).

**Comment by swapnilmmane** [comment]
Hi @nodiscc, thanks for your note.
Sorry, if I missed something while explaining something. 
Webiny is an open-source and free CMS similar to [Strapi](https://strapi.io/). 
It is Serverless by nature and uses the AWS services like Lambda, DynamoDB, S3, CloudFront, etc. All these AWS offers a reasonably great free tier. 
Users can self-host Webiny on their AWS cloud. 

Please let me know if you would like me to cover any specific aspect of deployment, thank you!

**Pull request closed without merging**
