### PR TITLE
Add Notifo to custom communication.

### PR DESCRIPTION
**Pull request by SebastianStehle**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

### CODE REVIEW

**Review by nodiscc — CHANGES_REQUESTED** [review]
Sorry for the delay

- The main website does not mention that it can be self-hosted. Please use the source code link as the main link
- The onloy supported installation method is Docker -> please replace `C#` with `Docker`
- Can you point to the source code of the FROM images used in https://github.com/notifo-io/notifo/blob/main/Dockerfile?

Thanks

**Comment by SebastianStehle** [comment]
Hi,

thanks for your comment.

> The main website does not mention that it can be self-hosted. Please use the source code link as the main link
Makes sense, I have fixed that.

> The onloy supported installation method is Docker -> please replace C# with Docker
It is a ASP.NET Core application, which can be installed everywhere. It would make more sense to replace C# with ASP.NET Core.

> Can you point to the source code of the FROM images used in https://github.com/notifo-io/notifo/blob/main/Dockerfile?
Where would you do that? Do you have examples for that?

**Comment by nodiscc** [comment]
> use the source code link as the main link
>>  Makes sense, I have fixed that.

Thanks :+1: 

>  It is a ASP.NET Core application, which can be installed everywhere. It would make more sense to replace C# with ASP.NET Core.

https://github.com/notifo-io/notifo/wiki/Installation#other-platforms documentation on non-Docker installation is very sparse, does not feel like a first class option, but it still looks possible. Maybe it should be `Docker/C#` ?

We don't have an `ASP.NET` tag so `C#` is fine.

> point to the source code of the FROM images used in https://github.com/notifo-io/notifo/blob/main/Dockerfile?
>Where would you do that? Do you have examples for that?

Please just post links to sources of these images here, it's not clear to me that everything in there is FOSS, I could just use [`FROM mcr.microsoft.com/windows:20H2`](https://hub.docker.com/_/microsoft-windows) in a Dockerfile, it does not make the app Free/Open-Source :) I could not find the source for `mcr.microsoft.com/dotnet/sdk:6.0` and `mcr.microsoft.com/dotnet/aspnet:6.0.0-bullseye-slim` and dockerhub does not make it easy.

**Comment by SebastianStehle** [comment]
The SDK image is this one: https://github.com/dotnet/dotnet-docker/blob/42572e95ee77658a45664e928264e7499b2a1d77/src/sdk/6.0/bullseye-slim/amd64/Dockerfile

The runtime image is this one: https://github.com/dotnet/dotnet-docker/blob/42572e95ee77658a45664e928264e7499b2a1d77/src/runtime/6.0/bullseye-slim/amd64/Dockerfile

**Review by nodiscc — APPROVED** [review]

**Pull request merged**
